spring.application.name=secure-note-app
# Server
spring.data.mongodb.uri=${MONGO_URI}
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

server.port=${PORT:8080}

# Logging
logging.level.org.springframework.security=INFO