spring.application.name=secure-note-app
# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://pillalakarthik7895:Karthik-0112@cluster0.zz12jtg.mongodb.net/

# JWT
jwt.secret=Zuk5KazbagqZ6A6BcC77yDGM3Rj1KZNWWGy1xNKVLLK
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG