spring.application.name=secure-note-app
# Server
spring.data.mongodb.uri=mongodb+srv://pillalakarthik7895:0Y6MISGRzn7w2T5Q@cluster0.zz12jtg.mongodb.net/
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

server.port=${PORT:8080}

# Logging
logging.level.org.springframework.security=DEBUG
spring.main.banner-mode=off